# .github/workflows/auto-commit.yml

name: Daily Profile Activity

permissions:
  contents: write

on:
  schedule:
    - cron: "0 12 * * 6,0,1,2,3,4" # 6 PM Bangladesh time (UTC+6)
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update Activity File
        run: |
          echo "Last activity: $(date)" >> activity.log

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "firadfd833@gmail.com"
          git add activity.log
          git commit -m "chore: daily activity commit $(date)" || echo "No changes"
          git push origin main
