name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Run once a day at midnight UTC
  workflow_dispatch:     # Allow manual runs
  push:
    branches:
      - main # Run on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for pushing to gh-pages
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: firadfd
          outputs: dist/snake.svg

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Use default GITHUB_TOKEN
          publish_dir: ./dist
